import { normalizeMappingType } from './mappingRulePolicy';
import type { GeneratedColumn, GeneratedTable, GoldenFmdStructure, HistoricalSheet } from '../types/entities';

/** Deterministic classification of a historical FMD sheet's columns against the Golden FMD's
 * default field categories (Source/Mapping/Target — the shape migration 0017 seeds), plus pure-JS
 * row building. Row building never depends on AI succeeding: every historical column that matches
 * a pattern gets copied straight across; only the transformation-rule text for rows that don't
 * already have one is generated by AI (see aiHistoricalConvert.ts), batched and defaulting to
 * "Copy 1:1" if that fails — so a conversion can degrade, but never fail outright. Assumes the live
 * Golden FMD still uses the default field names; a heavily renamed Golden structure would leave
 * those specific columns blank rather than mis-map, which is the safe direction to fail in. */

type Role =
  | 'SRC_SYSTEM' | 'SRC_TABLE' | 'SRC_FIELD' | 'SRC_FIELD_DESC' | 'SRC_MANDATORY' | 'SRC_DATATYPE' | 'SRC_LENGTH' | 'SRC_DECIMAL' | 'SRC_CHECK_TABLE'
  | 'MAPPING_TYPE'
  | 'TGT_SYSTEM' | 'TGT_TABLE' | 'TGT_FIELD' | 'TGT_FIELD_DESC' | 'TGT_MANDATORY' | 'TGT_DATATYPE' | 'TGT_LENGTH' | 'TGT_DECIMAL' | 'TGT_CHECK_TABLE';

const SIDE_PATTERNS: [RegExp, Role][] = [
  [/table/i, 'SRC_TABLE'],
  [/field.*name/i, 'SRC_FIELD'],
  [/field.*desc/i, 'SRC_FIELD_DESC'],
  [/mandatory/i, 'SRC_MANDATORY'],
  [/data.*type/i, 'SRC_DATATYPE'],
  [/\blength\b/i, 'SRC_LENGTH'],
  [/decimal/i, 'SRC_DECIMAL'],
  [/check.*table/i, 'SRC_CHECK_TABLE'],
];
const asTarget = (role: Role): Role => role.replace('SRC_', 'TGT_') as Role;
const SYSTEM_PATTERN = /system/i;
const TARGET_HINT = /target/i;
const MAPPING_TYPE_PATTERN = /mapping\s*(rule|type)/i;

// MAPPING_TYPE enum + free-text normalizer now live in mappingRulePolicy.ts — the same canonical
// COPY/TRANSFORM/XREF/DEFAULT set used by Standard-generation defaults and the Custom FMD Mapping
// Review, re-exported here so existing imports of MAPPING_TYPE_VALUES/normalizeMappingType from
// this module keep working.
export { MAPPING_TYPE_VALUES, normalizeMappingType, type MappingType } from './mappingRulePolicy';

/** Column index for each recognized role, or undefined if this sheet has no matching column.
 * Walks headers left to right, flipping from "source" to "target" readings the first time a
 * header mentions "target" — real FMD headers are laid out source-columns-then-target-columns, so
 * position (not a fixed exact label) is what actually disambiguates "Mandatory" appearing once vs.
 * "Source/Target Mandatory" appearing twice. */
export function classifyHeaders(headers: string[]): Partial<Record<Role, number>> {
  const roles: Partial<Record<Role, number>> = {};
  let side: 'source' | 'target' = 'source';

  headers.forEach((raw, i) => {
    const h = (raw ?? '').split('\n')[0] ?? '';
    if (TARGET_HINT.test(h)) side = 'target';

    if (SYSTEM_PATTERN.test(h)) {
      const role = side === 'source' ? 'SRC_SYSTEM' : 'TGT_SYSTEM';
      if (roles[role] === undefined) { roles[role] = i; return; }
    }
    for (const [re, srcRole] of SIDE_PATTERNS) {
      if (!re.test(h)) continue;
      const role = side === 'source' ? srcRole : asTarget(srcRole);
      if (roles[role] === undefined) { roles[role] = i; return; }
    }
    if (roles.MAPPING_TYPE === undefined && MAPPING_TYPE_PATTERN.test(h)) roles.MAPPING_TYPE = i;
  });

  return roles;
}

export interface ClassifiedRow { fields: Record<string, string>; needsRule: boolean }

/** Builds one Golden-schema row per historical data row — `sheet` here is already the per-plant
 * slice from plantSplit.ts, whose last one or two columns are always literally named "Mapping
 * Rule" / "Comments" by construction (no need to re-classify those). */
export function buildRowsFromClassification(sheet: HistoricalSheet, roles: Partial<Record<Role, number>>): ClassifiedRow[] {
  const ruleColIndex = sheet.headers.indexOf('Mapping Rule');
  const commentColIndex = sheet.headers.indexOf('Comments');
  const get = (row: string[], role: Role): string => {
    const idx = roles[role];
    return idx === undefined ? '' : (row[idx] ?? '').trim();
  };

  return sheet.rows.map((row) => {
    const transformationRule = ruleColIndex === -1 ? '' : (row[ruleColIndex] ?? '').trim();
    const fields: Record<string, string> = {
      SRC_SYSTEM: get(row, 'SRC_SYSTEM'), SRC_TABLE: get(row, 'SRC_TABLE'), SRC_FIELD: get(row, 'SRC_FIELD'), SRC_FIELD_DESC: get(row, 'SRC_FIELD_DESC'),
      SRC_FIELD_MANDATORY: get(row, 'SRC_MANDATORY'), SRC_FIELD_DATATYPE: get(row, 'SRC_DATATYPE'), SRC_FIELD_LENGTH: get(row, 'SRC_LENGTH'),
      SRC_FIELD_DECIMAL: get(row, 'SRC_DECIMAL'), SRC_CHECK_TABLE: get(row, 'SRC_CHECK_TABLE'),
      MAPPING_TYPE: normalizeMappingType(get(row, 'MAPPING_TYPE')),
      TRANSFORMATION_RULE: transformationRule,
      TECHNICAL_RULE: commentColIndex === -1 ? '' : (row[commentColIndex] ?? '').trim(),
      TGT_SYSTEM: get(row, 'TGT_SYSTEM'), TGT_TABLE: get(row, 'TGT_TABLE'), TGT_FIELD: get(row, 'TGT_FIELD'), TGT_FIELD_DESC: get(row, 'TGT_FIELD_DESC'),
      TGT_FIELD_MANDATORY: get(row, 'TGT_MANDATORY'), TGT_FIELD_DATATYPE: get(row, 'TGT_DATATYPE'), TGT_FIELD_LENGTH: get(row, 'TGT_LENGTH'),
      TGT_FIELD_DECIMAL: get(row, 'TGT_DECIMAL'), TGT_CHECK_TABLE: get(row, 'TGT_CHECK_TABLE'),
    };
    return { fields, needsRule: transformationRule === '' && (fields.SRC_FIELD !== '' || fields.TGT_FIELD !== '') };
  });
}

/** Golden structure's own field list, as the GeneratedColumn[] every generated FMD table uses —
 * unchanged regardless of how the row values were produced. */
export function goldenColumns(structure: GoldenFmdStructure): GeneratedColumn[] {
  return structure.sections.flatMap((s) => s.fields.map((f) => ({ field: f.field, sectionName: s.name, color: s.color, description: f.description, critical: f.critical || undefined, kind: f.kind, options: f.options })));
}

export function toGeneratedTable(structureId: string, structureIdent: string, structureDescription: string | undefined, rows: ClassifiedRow[]): GeneratedTable {
  return { structureId, structureIdent, structureDescription, rows: rows.map((r) => r.fields) };
}
